### ISSUE TITLE
don't make lightbox_size mandatory

### ISSUE THREAD

**Issue by fritzmg** [isotope/core#1830] opened 2017-07-28 19:18 UTC
If you want the full size version of a gallery image (on the product reader for example) to be the original image file, you would normally simply set no image size. However, the `lightbox_size` field is mandatory for some reason (even though it isn't defined as one in the DCA?), so when saving the gallery settings, you'll get an error (even though it will work in the end this way).

![lightbox_size](https://user-images.githubusercontent.com/4970961/28732959-31cca43a-73da-11e7-98c8-3f7611c1ce93.png)

**Comment by aschempp** [comment] 2017-08-23 08:27
I cannot reproduce this in the latest version?

**Comment by netzarbeiter** [comment] 2017-08-23 08:38
Can reproduce it on a 2.4.3.

**Comment by aschempp** [comment] 2017-08-23 09:50
Looks like a Contao bug to me: https://github.com/contao/core/issues/8776

**Comment by Aybee** [comment] 2017-08-23 10:12
But does this make sense to select proportional and leave both size fields empty? Without a selection you get no error.

**Comment by aschempp** [comment] 2017-08-23 17:02
I guess we need to add a blank option.

**Comment by aschempp** [comment] 2017-09-04 12:15
Fixed in f9939e5d0060708dadcd514784c1f34cd902f694

**Closed by aschempp** 2017-09-04 12:15 UTC
Labels: bug
