### ISSUE TITLE
Support dc multilingual 4.0

### ISSUE THREAD

**Issue by dmolineus** [isotope/core#2181] opened 2020-12-14 14:52 UTC
At the moment isotope is limited to version dc_multilingual `^2.0`. It would great if version `^4.0` would be supported as well.

**Comment by fritzmg** [comment] 2020-12-14 14:54
Duplicate of https://github.com/isotope/core/issues/2164 (https://github.com/isotope/core/issues/2179).

**Closed as completed** 2020-12-15 07:04 UTC
