### ISSUE TITLE
PayPal IPN fails with Exception

### ISSUE THREAD

**Issue by bennyborn** [isotope/core#1860] opened 2017-08-30 16:15 UTC
Hi there,

I'm working on a new shop using contao/core-bundle@4.4.3 and isotope/isotope-core@2.4.3
The whole payment process with PayPal itself seems to work fine but the System Log reads

```
Exception in post-sale request. See system/logs/isotope_postsale.log for details.
```

Quick look into the isotope_postsale.log states

```
[30-Aug-2017 17:34:56] Exception in post-sale request
#0 /notrelevant/vendor/isotope/isotope-core/system/modules/isotope/postsale.php(166): Haste\Http\Response\Response->send()
#1 /notrelevant/vendor/isotope/isotope-core/system/modules/isotope/postsale.php(240): Isotope\PostSale->run()
#2 {main}
```

I've seen this problem before, also using Isotope 2.4.3 but on a Contao 3.X installation.
AFAIR my only solution in 3.X was to comment out lines 165 and 166 and replace it with a

```
header("HTTP/1.1 200 OK");
```

Although the payment itself works fine, PayPal will start to contact the account holder as soon as there are too many failed IPNs which can be checked in the IPN History within PayPal.

I've got a few other Isotope Shops coming up in the near future so this should be a high priority issue to be fixed in the next bugfix release.

**Comment by aschempp** [comment] 2017-09-04 12:20
Duplicate of #1834

**Closed by aschempp** 2017-09-04 12:20 UTC
