### ISSUE TITLE
No more individual list templates (mod_iso)

### ISSUE THREAD

**Issue by eBlick** [isotope/core#2156] opened 2020-07-14 06:30 UTC
Current version Isotope 2.6.13, Contao 4.9.3

product list as well as product variant list.

no more mod_iso templates are visible.

<img width="421" alt="Bildschirmfoto 2020-07-14 um 08 27 34" src="https://user-images.githubusercontent.com/6641281/87392078-2d1acf80-c5ac-11ea-8555-50472b871f9c.png">

**Comment by fritzmg** [comment] 2020-07-14 07:27
I cannot confirm this problem. You probably have an extension installed that interferes with this.

**Comment by eBlick** [comment] 2020-07-14 08:08
I'll check this.

**Comment by eBlick** [comment] 2020-07-19 10:07
I just recognized it was contao 4.4.49 not 4.9.3 as mentioned.
Nevertheless, I updated Contao to 4.4.50 and checked all extensions and deleted them für debugging.
I attached a screenshot with the used extensions.
Still the mod_templates are **not** available for product variant lists.
They **are** available in product lists, though.

<img width="1182" alt="Bildschirmfoto 2020-07-19 um 12 03 41" src="https://user-images.githubusercontent.com/6641281/87872344-fd0e6a80-c9b7-11ea-943c-c4778ae01166.png">

**Comment by fritzmg** [comment] 2020-07-19 10:42
Ah I see now, I missed that you meant the product **variant** list.

The cause of this is because the type of the module is  `iso_productvariantlist`, however there is no `mod_iso_productvariantlist`, as the product variant list module uses the same template as the product list module.

In order to fix it, Isotope needs to implement its own options_callback for `tl_module.customTpl`, so that it can return the proper template group for both modules.

**Comment by aschempp** [comment] 2022-04-21 06:55
> In order to fix it, Isotope needs to implement its own options_callback for tl_module.customTpl, so that it can return the proper template group for both modules.

@fritzmg how is that supposed to work? I don't think I can override the options callback just for my module?

**Comment by aschempp** [comment] 2022-04-27 06:39
This bug has been fixed in Contao 4.9, and the upcoming Isotope 2.8 will only support Contao 4.9+, therefore I'm closing this ticket.

**Closed by aschempp** 2022-04-27 06:39 UTC
Labels: bug
