### ISSUE TITLE
Error updating from 2.6.15 to above versions

### ISSUE THREAD

**Issue by xApep** [isotope/core#2256] opened 2021-10-15 07:44 UTC
Hey,
I'm trying to update from 2.6.15 to 2.7.0 or above and I always get the same error.

```
Recoverable error: Argument 1 passed to Isotope\Model\AttributeOption::findByAttribute() must implement interface Isotope\Interfaces\IsotopeAttributeWithOptions, instance of Isotope\Model\Attribute\TextArea given, called in system/modules/isotope/library/Isotope/Model/Attribute.php on line 260 and defined in system/modules/isotope/library/Isotope/Model/AttributeOption.php on line 267

#0 system/modules/isotope/library/Isotope/Model/AttributeOption.php(267): __error(4096, 'Argument 1 pass...', '/Users/master/S...', 267, Array)
#1 system/modules/isotope/library/Isotope/Model/Attribute.php(260): Isotope\Model\AttributeOption::findByAttribute(Object(Isotope\Model\Attribute\TextArea), Array)
#2 system/modules/isotope/library/Isotope/Model/Attribute/TextArea.php(27): Isotope\Model\Attribute->saveToDCA(Array)
#3 system/modules/isotope/library/Isotope/Backend/Product/DcaManager.php(118): Isotope\Model\Attribute\TextArea->saveToDCA(Array)
#4 system/modules/isotope/library/Isotope/Backend/Product/DcaManager.php(40): Isotope\Backend\Product\DcaManager->addAttributes()
#5 system/modules/core/library/Contao/DcaLoader.php(102): Isotope\Backend\Product\DcaManager->initialize('tl_iso_product')
#6 system/modules/haste/library/Haste/Model/Relations.php(477): Contao\DcaLoader->load()
#7 system/modules/core/library/Contao/Database/Installer.php(410): Haste\Model\Relations->addRelationTables(Array)
#8 system/modules/core/library/Contao/DcaExtractor.php(429): Contao\Database\Installer->getFromFile()
#9 system/modules/core/library/Contao/DcaExtractor.php(128): Contao\DcaExtractor->createExtract()
#10 system/modules/core/library/Contao/DcaExtractor.php(144): Contao\DcaExtractor->__construct('tl_page')
#11 system/modules/core/library/Contao/Model.php(114): Contao\DcaExtractor::getInstance('tl_page')
#12 system/modules/core/classes/Backend.php(690): Contao\Model->__construct(Object(Contao\Database\Mysqli\Result))
#13 system/modules/core/library/Contao/Automator.php(399): Contao\Backend::findSearchablePages('1', '', true)
#14 system/modules/core/library/Contao/Automator.php(256): Contao\Automator->generateSitemap()
#15 system/modules/core/classes/PurgeData.php(77): Contao\Automator->generateXmlFiles()
#16 system/modules/core/modules/ModuleMaintenance.php(52): Contao\PurgeData->run()
#17 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#18 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#19 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#20 contao/main.php(20): Contao\BackendMain->run()
#21 {main}

Fatal error: Call to undefined method Isotope\Model\Attribute\TextArea::getOptionsSource() in system/modules/isotope/library/Isotope/Model/AttributeOption.php on line 269
```
This shop is still on Contao 3.5.40. I update it via copy/paste isotope core. I have also manually updated:

```
"terminal42/contao-conditionalselectmenu":"^3.0.3",
"terminal42/dcawizard": "~2.3",
"codefog/contao-haste": "^4.24.3",
"menatwork/contao-multicolumnwizard": "~3.2",
"terminal42/contao-tablelookupwizard": "~3.2",
```

but the problem still persist. Any idea what I'm missing?

**Comment by fritzmg** [comment] 2021-10-15 07:50
Duplicate of #2191.

**Closed as completed** 2021-10-20 08:44 UTC
