### ISSUE TITLE
Paypal IPN error code 500

### ISSUE THREAD

**Issue by chberger** [isotope/core#2058] opened 2019-08-05 21:41 UTC
Hi Isotope-Team,

I suffer from an issue which is somehow related to the Paypal IPN implementation. In my case the postsale script always returns 500, although the processing went just fine. I can see the 'IPN data accepted' entry in my log file as well.

05.08.2019 22:52] PayPal IPN: data accepted  
[05.08.2019 22:52] New post-sale request: system/modules/isotope/postsale.php?mod=pay&id=2

In addition, the order status gets updated and all that stuff. So we actually go through the whole implementation of processPostsale (please see PayPal class for more details). This 'IPN data accepted' log is written at the very end. In case of any error I would expect another log statement. However, since the script returns 500, Paypal sends IPNs again and again..

I've also checked the isotope-postsale log but it contains just the paypal data without any error indicator. Anyway, I was able to reproduce that 500 error code while sending the captured data again to my endpoint:
![image](https://user-images.githubusercontent.com/3606282/62496238-9c067a80-b7d8-11e9-8c66-26bf6aacf05b.png)

Endpoint: https://..../system/modules/isotope/postsale.php?mod=pay&id=2
HTTP-Method: POST
Body data: taken from isotope-postsale.log 

While repeating it in debug mode I got this stack trace:
Endpoint: https://.../app_dev.php/system/modules/isotope/postsale.php?mod=pay&id=2

(2/2)                                    InternalServerErrorHttpException                                                                Invalid request token. Please reload the page and try again.
--
in ExceptionConverterListener.php line 109
at ExceptionConverterListener->convertToHttpException(object(InvalidRequestTokenException), 'InternalServerErrorHttpException')in ExceptionConverterListener.php line 71
at ExceptionConverterListener->onKernelException(object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))in WrappedListener.php line 115
at WrappedListener->__invoke(object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))in EventDispatcher.php line 212
at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(GetResponseForExceptionEvent))in EventDispatcher.php line 44
at EventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent))in TraceableEventDispatcher.php line 143
at TraceableEventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent))in HttpKernel.php line 228
at HttpKernel->handleException(object(InvalidRequestTokenException), object(Request), 1)in HttpKernel.php line 79
at HttpKernel->handle(object(Request), 1, true)in Kernel.php line 200
at Kernel->handle(object(Request))in app_dev.php line 69

(1/2)                                    InvalidRequestTokenException                                                                Invalid request token. Please reload the page and try again.
--
in ContaoFramework.php line 463
at ContaoFramework->handleRequestToken()in ContaoFramework.php line 336
at ContaoFramework->initializeFramework()in ContaoFramework.php line 159
at ContaoFramework->initialize()in ContaoUserProvider.php line 70
at ContaoUserProvider->loadUserByUsername('frontend')in ContaoAuthenticator.php line 85
at ContaoAuthenticator->authenticateToken(object(AnonymousToken), object(ContaoUserProvider), 'backend')in SimpleAuthenticationProvider.php line 42
at SimpleAuthenticationProvider->authenticate(object(AnonymousToken))in AuthenticationProviderManager.php line 76
at AuthenticationProviderManager->authenticate(object(AnonymousToken))in SimplePreAuthenticationListener.php line 101
at SimplePreAuthenticationListener->handle(object(GetResponseEvent))in WrappedListener.php line 46
at WrappedListener->handle(object(GetResponseEvent))in TraceableFirewallListener.php line 35
at TraceableFirewallListener->handleRequest(object(GetResponseEvent), object(Generator))in Firewall.php line 84
at Firewall->onKernelRequest(object(GetResponseEvent))in FirewallListener.php line 48
at FirewallListener->onKernelRequest(object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher))in WrappedListener.php line 115
at WrappedListener->__invoke(object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher))in EventDispatcher.php line 212
at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(GetResponseEvent))in EventDispatcher.php line 44
at EventDispatcher->dispatch('kernel.request', object(GetResponseEvent))in TraceableEventDispatcher.php line 143
at TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent))in HttpKernel.php line 127
at HttpKernel->handleRaw(object(Request), 1)in HttpKernel.php line 68
at HttpKernel->handle(object(Request), 1, true)in Kernel.php line 200
at Kernel->handle(object(Request))in app_dev.php line 69

So for me it seems like the request token is still verified. However, based on the postsale implementation this should not happen:

/**
 * Set the script name
 */
define('TL_SCRIPT', 'system/modules/isotope/postsale.php');
/**
 * Initialize the system
 */
define('TL_MODE', 'FE');
define('BYPASS_TOKEN_CHECK', true);

According to my IPN history the last working IPN check was on 11th of July. Since that I did not change any Paypal sttings ...

System setup:
Contao: 4.4.41
Isotope: 2.5.15

Any help would be appreciated.

**Comment by aschempp** [comment] 2019-08-06 06:05
I just checked the Contao code, and the `BYPASS_TOKEN_CHECK` constant should be correctly handled. In Contao 4.4, this is still done by the `Contao\RequestToken` class. Maybe you can try to debug why that line does not work?

**Comment by chberger** [comment] 2019-08-11 19:42
Yeah, the BYPASS_TOKEN_CHECK seems not to be the root cause. Anyway, there is something really strange .. That's what I've figured out:

URL: /system/modules/isotope/postsale.php?mod=pay&id=2 

ContaoFramework->canSkipTokenCheck(): Result:Yes --> Since this is yes RequestToken.php->validate() will be skipped, so BYPASS_TOKEN_CHECK  is just ignored
Postsale.php->run: BYPASS_TOKEN_CHECK defined!
PayPal.php->processPostsale(): BYPASS_TOKEN_CHECK defined!
Anyway, some code afterwards returns the error code 500 

It's very difficult the figure out which code returns 500, because when I enable the debug mode the routing is different:

URL app_dev.php/system/modules/isotope/postsale.php?mod=pay&id=2

ContaoFramework->canSkipTokenCheck(): Result:No (this check is false now)
RequestToken.php->validate(): BYPASS_TOKEN_CHECK not defined! (why is the constant not defined in debug mode?)
Invalid request token. Please reload the page and try again. 

When I set BYPASS_TOKEN_CHECK to true in RequestToken.php->validate() to pass the validation I get a PageNotFoundException. So I don't know how to continue ... However, it seems like this is a Contao core issue. Shall I raise a bug in the Contao repo?

**Comment by aschempp** [comment] 2019-08-12 06:20
Thanks for debugging this! I'm not sure it's a core issue, and without more information the core team couldn't help with it either. Have you checked to see if there is anything in the log files? A 500 is usually a server error that should be logged, either by Symfony or by the webserver.

**Comment by chberger** [comment] 2019-08-12 18:32
Unfortunately, there is nothing in the log file. The only file which is getting updated is isotope_postsale.log but just with the expected content. Not a single line is written into the prod-*.log.

I've also checked the log file from my webserver. But this is also not really helpful ...
2003:7f:8f00:df00:xxxxx:xxxxx:xxxx:xxxx- - [12/Aug/2019:20:11:29 +0200] "POST /system/modules/isotope/postsale.php?mod=pay&id=2 HTTP/1.1" 500 0 "-" "Mozilla" "www.****.de"

Response:
![grafik](https://user-images.githubusercontent.com/3606282/62888046-cdce9280-bd3e-11e9-93e6-55a58d5a60a4.png)

Anyway, I'll try to copy my setup to my local machine where I can do some real debugging. I guess everything else is just like searching the needle in the haystack ..

**Comment by Mynyx** [comment] 2019-08-24 11:23
PayPal sends an email and threatens to disable the IPN functionality for the account due to the status code 500.

It would therefore be very helpful if a solution to this problem could be found soon.

**Comment by chberger** [comment] 2019-08-24 11:28
Yes I know. The problem is I'm very busy at the moment and it will take some time to reproduce the issue locally. Right now I don't see any chance to track down the issue on my webspace since the debug mode behaves differently ...

**Comment by Mynyx** [comment] 2019-08-26 16:52
The error also occurs if the function run() in the class PostSale is replaced as follows:
````
    /**
     * Run the controller
     */
    public function run()
    {
        $objResponse = new Response();
        $objResponse->send();
    }
````
It disappears when the line ```$objResponse->send();``` is commented out.

Therefore it is not a bug in the PayPal module, it must be a more general bug. But I couldn't find anything in the log files too.

**Comment by chberger** [comment] 2019-09-01 14:08
Thanks @Mynyx . Now we're getting closer :-) 

I've analysed the send method of that Haste\Http\Response class and now it makes sense.  In my case, the statement ($blnExit && class_exists('Contao\CoreBundle\Exception\ResponseException')) evaluates to true and thus it throws that ResponseException which then actually leads to the 500 error code.

` /**
     * Send the response
     *
     * @param bool $blnExit Exit script
     *
     * @return Response|null
     */
    public function send($blnExit = true)
    {
        $this->prepare();

        if ($blnExit && class_exists('Contao\CoreBundle\Exception\ResponseException')) {
            // seems to be the root cause for the 500 error code
            throw new ResponseException(
                new SymfonyResponse($this->strContent, $this->intStatus, $this->arrHeaders)
            );
        }
        // Clean the output buffer
        ob_end_clean();
        // Send
        $this->sendHeaders();
        echo $this->strContent;
        if ($blnExit) {
            exit;
        }
        return $this;
    }`

Actually I don't understand the purpose of this code. `$blnExit` is true by default and this `class_exists` check makes no sense to me. Anyway, when I change the postsale script call as follow, then it works:

`  
/**
     * Run the controller
     */
    public function run()
    {
        // code removed for better readability 
        $objResponse = new Response();
        **$objResponse->send(false);**

        } catch (\Exception $e) {
            if (is_a($e, 'Contao\CoreBundle\Exception\ResponseException')) {
                throw $e;
            }
            \System::log(
                'Exception in post-sale request. See system/logs/isotope_postsale.log for details.',
                __METHOD__,
                TL_ERROR
            );

            log_message((string) $e, 'isotope_postsale.log');

            $objResponse = new Response('Internal Server Error', 500);
            $objResponse->send();
        }
    }
`

**Comment by fritzmg** [comment] 2019-09-01 14:40
That would be related to https://github.com/isotope/core/issues/1993 then.

**Comment by aschempp** [comment] 2019-09-01 14:52
This should be fixed sind Contao 4.4.41 though?

**Comment by Mynyx** [comment] 2019-09-24 19:00
@aschempp Do you need further information of this issue?

**Comment by Sehiro** [comment] 2019-10-21 14:24
As of today this is not fixed, right? I updated a couple of days ago and started having that problem. So after finding a workaround and wanting to report it, I found this issue and I'd like to share my findings:

I think chberger in his post from sep 1st is not 100% correct, as the Exception thrown there kinda makes sense but is handled incorrectly later.

The problem is that $objResponse->send() in postsale.php is (correctly?) throwing an ResponseException which should make the InitializeController return the HTTPCode of 200. Problem is, that in InitializeController.php the Exception which is cought/evaluated does not implement HttpExceptionInterface and therefore a returncode of 500 is set. I have not gone into further details where the Interface needs to be implemented as I went with a workaround in postsale.php.

InitializeController.php:
```
private function handleException(\Exception $e, Request $request, $type)
    {
....
           if ($e instanceof HttpExceptionInterface) {
                // Keep the HTTP status code and headers
                $response->setStatusCode($e->getStatusCode());
                $response->headers->add($e->getHeaders());
            } else {
                $response->setStatusCode(500);
            }
....
```

My workaround is (as metioned) a fix in postsale.php but I would exit after the response is actually sent with $objResponse->send(false); because we do not want anything else to be sent afterwards. So my workaround: 
```

    public function run()
    {
      ...

        $objResponse = new Response();
        $objResponse->send(false);
        exit();

        ...
    }
```

cheers
Stefan

**Comment by operatorone** [comment] 2019-11-26 13:19
Is this issue to be fixed in 2.6.4? I have kind of similar problems of the order status switching by itself back to pending when another paypal order is placed.

**Comment by aschempp** [comment] 2019-11-27 08:29
This could be related to https://github.com/contao/contao/pull/1020, let's see if it's fixed in the next Contao version

**Comment by operatorone** [comment] 2019-12-05 09:48
Will this fix also be in the Contao 4.4.X LTS? Because I have more and more trouble with Paypal. Right now orders are charged twice by Paypal and the money has be be sent back to the customer.

**Comment by aschempp** [comment] 2019-12-09 14:47
The mentioned PR **is** for Contao 4.4 …

**Comment by operatorone** [comment] 2019-12-09 15:39
So, not neccessary in 4.8 for instance?

**Comment by operatorone** [comment] 2019-12-09 16:27
By the way, what means **PR**?

**Comment by netzarbeiter** [comment] 2019-12-09 16:29
PR means [Pull Request](https://de.wikipedia.org/wiki/Pull_Request).

**Comment by operatorone** [comment] 2019-12-12 11:04
Is it neccessary for 4.8 and is the error here fixed yet?

**Comment by aschempp** [comment] 2019-12-16 15:34
I have also improved this in 56b8b9e01522588a32263c89d48830c13bba1b5f so orders are not changed after they are placed.

**Closed by aschempp** 2019-12-16 15:34 UTC
Labels: bug

**Comment by swinde** [comment] 2019-12-19 09:21
I updated Contao to 4.4.46 yesterday.
Today around 9.30 am I found Paypal IPN error code 500 in the log file.
At the same time, a canceled PayPal order was automatically converted back to new, with all associated email notifications!
The Pullrequest contao / core #1020 is, as I have seen, included in 4.4.46!

**Comment by aschempp** [comment] 2019-12-20 10:30
contao/contao#1020 does not prevent "multiple executions" of postsale requests, it is intended to make sure Paypal (and others) get correctly notified that the IPN has been processed, so it's not sent over and over again. Hotfix 2.6.5 will prevent orders from being changed by IPN after they have been placed.

**Comment by operatorone** [comment] 2019-12-28 21:22
How can I apply the hotfix?

**Comment by swinde** [comment] 2019-12-30 09:02
in the Contao Manager at Isotope change and update the version setting in "dev-hotfix / 2.6.5 as 2.6.4".

**Comment by operatorone** [comment] 2019-12-30 09:16
Thanks for the tip. May be a stupid question, but where do I put the line **dev-hotfix / 2.6.5 as 2.6.4**? In the composer.json or where? When I put it in the Contao Manager in the version field, it's not exepted.

**Comment by swinde** [comment] 2019-12-30 11:10
dev-hotfix/2.6.5 as 2.6.4

**Comment by operatorone** [comment] 2019-12-30 13:03
**Thanks for your help.** 

I applied the hotfix and switched the order status after receiving the order. Till now it doesn't jump back to "pending". What is good.

I also checked the page "Verlaufsseite für sofortige Zahlungsbestätigungen (IPN)" at Paypal and within the transaction I found these infos:

- HTTP-Rückmeldungscode 500
- Zustellstatus Neuer Versuch...
- Anz. der erneuten Versuche 6

I will monitor this and hopefully it will work this time. My customer is getting more and more upset because of this problem.

**Comment by operatorone** [comment] 2019-12-30 13:25
Unfortunately the amount of retries is growing at the page "Verlaufsseite für sofortige Zahlungsbestätigungen (IPN)"

- Anz. der erneuten Versuche 8

The result will be, that Paypal stops the "sofortige Zahlungsbestätigungen" because of to many retries. 

**What could be the problem, that isotope does not respond properly to this request?**

**Comment by netzarbeiter** [comment] 2019-12-30 13:48
**me:** A programmer would have to look at that.
**you:** When can a programmer look at this.
**me:** No idea.
**you:** But I need a solution as soon as possible, because my customer is already very unhappy.
**me:** Join the [Isotope eCommerce Circle](https://isotopeecommerce.org/en/circle.html) and get professional support.

**Comment by aschempp** [comment] 2020-01-17 10:01
we have found that this issue might still occur in Contao 4.4 (but not the latest Contao version). If you use Contao 4.4, you need to update to 4.4.47 as soon as https://github.com/contao/contao/pull/1204 has been merged and released.
