### ISSUE TITLE
Product List and Reader

### ISSUE THREAD

**Issue by rburch** [isotope/core#1495] opened 2015-07-28 09:58 UTC
I'm not sure if this is a bug or if I'm doing something wrong. I'm using Contao 3.5.0 and Isotope 2.3.0.6002-RC. I have a Product list set up and am using a separate reader page. I have the list page set to use the reader page and am pointing to it. When I click view details in the list the url doesn't resolve. If I turn off the reader page it works but I want to use a different layout for the list than the full product info.

**Comment by aschempp** [comment] 2015-07-30 05:34
Duplicate of https://github.com/isotope/core/issues/1463

**Closed by aschempp** 2015-07-30 05:34 UTC
Labels: duplicate
