### ISSUE TITLE
[2.4.4] bug - last option for shipping address not saved when using billing address equals shipping address

### ISSUE THREAD

**Issue by paulhaem** [isotope/core#1874] opened 2017-10-08 15:55 UTC
Hello,
following steps to reproduce:

1. Set option "Use member address as billing address if user is logged in" in the checkout module.
2. Make an order with an shipping address **different** to the billing address.
3. Make an order with an shipping address **equals** to the billing address.
4. Make an order ... 

Now you see, that the address settings are pre-set to the ones of point 2 not the ones from the last order (point 3).

Was reproduced using the Isotope demo.

Contao 3.5.30
Isotope 2.4.4

**Comment by aschempp** [comment] 2017-10-10 06:38
Do you mean the checkout module always shows "enter shipping address" when the billing address is fixed on the member address?

**Comment by paulhaem** [comment] 2017-10-10 18:22
When you pick _billing address equals shipping address_, it will not pick this option the next time you make an order. Instead it will automatically pick the address from the address book you used when you didn't check the option _billing address equals shipping address_. The checkout module does not recognize this option as a valid state to preselect when making a new order.

**Comment by aschempp** [comment] 2017-10-11 06:52
Did you enable the "Default billing address" option? Then that's the intended case…

**Comment by paulhaem** [comment] 2017-10-11 09:31
Did you mean the "Use member address as billing address if user is logged in" option in the checkout module?

**Comment by aschempp** [comment] 2017-10-11 10:02
No. There's a checkbox field that you can enable in the shop configuration for each address. Each user can have a default billing and default shipping address that will be preselected on checkout.

**Comment by paulhaem** [comment] 2017-10-11 10:34
Oh, I see. I am using the default Isotope demo configuration, so `isDefaultBilling` and `isDefaultShipping` are both deactivated in the default shop configuration (CHF).

**Comment by aschempp** [comment] 2018-04-12 06:34
I was unable to reproduce this. I'm closing this ticket as it's probably outdated by now.

**Closed by aschempp** 2018-04-12 06:34 UTC
Labels: bug
