### ISSUE TITLE
Back button issues concerning the cart module

### ISSUE THREAD

**Issue by Defcon0** [isotope/core#1528] opened 2015-09-15 15:18 UTC
Hello,

I think there's a serious issue with the back button that happens at least in Chrome (in Firefox it works).

What to do:
- go to some website containing a product list which has an "add to cart"-button for each product
- click on the "add to cart"-button -> the user is redirected to the cart page (containing a cart module)
- now click the back button of your browser and look at the markup in the console (screenshot attached)

What can you see:
![bug](https://cloud.githubusercontent.com/assets/1485098/9880750/3fee5904-5bcd-11e5-8190-52bb1ca5bd29.png)

--> The FORM_SUBMIT-hidden contains some false formId. The form-id is correct on the other hand. 

Here's the markup of the template:

	<form action="<?php echo $this->action; ?>" id="<?php echo $this->formId; ?>" name="iso<?php echo rand(); ?>" method="post" enctype="<?php echo $this->enctype; ?>" class="slick">
		<div class="formbody">
		<p><?php echo $this->formId; ?></p>
			<input type="hidden" name="FORM_SUBMIT" value="<?php echo $this->formId; ?>">

This seems *very* odd to me since $this->formId is written in all relevant fields. Now when I click the "add-to-cart"-button again, the wrong article is added to the cart.

Tested in Chrome (latest ubuntu-version), in Firefox it works.

**Comment by Zeromax** [comment] 2015-09-15 17:10
Which isotope Version?

**Comment by Defcon0** [comment] 2015-09-15 17:43
2.3.1

**Comment by aschempp** [comment] 2016-02-29 14:51
This seems to be a browser issue, has anyone been able to reproduce it?

**Comment by aschempp** [comment] 2016-04-02 05:57
I'm closing this, please reopen if there is new information.

**Closed by aschempp** 2016-04-02 05:57 UTC
