### ISSUE TITLE
Error after update to 2.7.1

### ISSUE THREAD

**Issue by operatorone** [isotope/core#2217] opened 2021-04-07 10:39 UTC
After I updated a complete system to 4.9.13 and update all extensions I get an error on cache warmup with isotope 2.7.1.

`Argument 1 passed to Isotope\Model\AttributeOption::findByAttribute() must implement interface Isotope\Interfaces\IsotopeAttributeWithOptions, instance of Isotope\Model\Attribute\TextField given, called in /home/www/contao4_u pd/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Attribute.php on line 260`

This is the lines from my composer.json
`"isotope/isotope-core": "2.7.*",`

**Comment by fritzmg** [comment] 2021-04-07 17:34
Duplicate of #2191

**Closed as completed** 2021-05-10 10:04 UTC
