### ISSUE TITLE
[Contao 4] Error when changing order status

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1773] opened 2017-02-11 14:55 UTC
I have chosen a template folder in "Store configuration" (Store configuration > Configuration > Template folder) and placed template "iso_collection_default" in this folder.

In the "Notification Center" there is a notification (Type: Order status change) with this template chosen.

Now I want to change the order status from an order and receive the following error:
`[2017-02-11 15:30:31] app.CRITICAL: An exception occurred. {"exception":"[object] (Exception(code: 0): Could not find template \"iso_collection_notification\" at /home/public_html/domain.com/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php:157)"} []`

After making a copy of the "iso_collection_default" template and place it in root template folder, it works like a charm. Bug or feature?

**Comment by aschempp** [comment] 2017-03-06 14:08
Unfortunately, this is something we most likely cannot change. @Toflar any idea?

**Comment by Toflar** [comment] 2017-03-06 14:10
There's no theme-context in the back end so templates cannot work there really. We could maybe store the theme id just like the store id when an order is submitted and try to load it where needed.

**Comment by aschempp** [comment] 2017-03-06 15:41
Well that's not the issue, because the template is configured in the store (and we have the store ID). But the notification is sent by Notification Center, therefore we don't use the Isotope/Template. Or am I wrong?

**Comment by Toflar** [comment] 2017-03-06 15:52
Not sure, you'll have to reproduce it. Imho we use the [correct template class](https://github.com/isotope/core/blob/9c594727918360a73151605600c4fec26490edbc/system/modules/isotope/library/Isotope/Model/ProductCollection/Order.php#L459). But it uses `Isotope::getConfig()->templateGroup` which does not exist in the back end context.

**Comment by aschempp** [comment] 2017-03-07 11:19
Thanks for the hint. Should be fixed in 9700b68846677513181a1f16b6425964e1f82acb

**Closed by aschempp** 2017-03-07 11:19 UTC
Labels: bug
