### ISSUE TITLE
Execute Order: Fatal Error

### ISSUE THREAD

**Issue by Irontale** [isotope/core#1676] opened 2016-07-12 08:48 UTC
After reviewing an order and submitting the form, I get following error message:

`Fatal error: Uncaught exception RuntimeException with message The registry already contains an instance for tl_iso_address::id() thrown in system/modules/core/library/Contao/Model/Registry.php on line 180`

I get a notification message with the corresponding attachted document via mail, but the order won't be created in the backend. I don't know if it has anything to do with this, but it worked properly before I added the notification and before I truncated the collection tables.

EDIT:
It looks like I am not the only one with this problem. Maybe it helps:
https://community.contao.org/de/showthread.php?58444-Hilfe-bei-Best%E4tigungsmail-(Contao-3-5-Isotope-2-3-0)&p=402985&viewfull=1#post402985

**Comment by aschempp** [comment] 2016-07-15 07:37
Which Isotope version are you using?

**Comment by Irontale** [comment] 2016-07-18 07:04
Sorry, I forgot to mention.

Contao: 3.5.12
Isotope: 2.3.5.9006

After removing the notification from the Checkout module, it's working properly.

**Comment by qzminski** [comment] 2016-08-12 09:01
@Irontale I can't reproduce it but can you try 4162ab4?

**Comment by aschempp** [comment] 2016-08-30 12:37
Probably fixed by @qzminski

**Closed by aschempp** 2016-08-30 12:37 UTC
Labels: bug
