### ISSUE TITLE
"Save and duplicate" button does not work everywhere

### ISSUE THREAD

**Issue by contaoacademy** [isotope/core#2323] opened 2022-07-13 11:53 UTC
- Contao 4.13.6
- PHP 8.1
- Isotope 2.8.5

I noticed that the «Save and duplicate» button does not always work correctly.

Especially in the store configuration, it happens almost everywhere that after clicking the button I only end up in the overview and nothing is duplicated.

**Steps to reproduce the error**
1. create new shipping method 
2. Save and duplicate

This also happens among others:
- tax rates
- tax classes
- shipping methods
- payment methods
- attributes
- product types

**Comment by aschempp** [comment] 2022-07-14 07:57
Can you test if this has been fixed in the latest dev branch (specifically by daee4bc776295e00b48506a2a5cbccfecb401188)?

**Comment by contaoacademy** [comment] 2022-07-14 08:24
I have installed `2.8.x-dev`, but there the problem persists.

**Comment by aschempp** [comment] 2023-02-27 07:13
I just tested this in the latest version and was unable to reproduce. Let me know if you still experience it.

**Comment by contaoacademy** [comment] 2023-03-09 12:25
The problem still persists for me in Contao Version 4.13.16, PHP 8.1 and Isotope 2.8.10.
Save and duplicate doesn't work.

**Comment by aschempp** [comment] 2023-03-30 10:33
Finally fixed in 284ae45709eaa797e7e8eace9d6c82f1f680773e

**Closed as completed by aschempp** 2023-03-30 10:33 UTC
Labels: bug

**Comment by contaoacademy** [comment] 2023-04-03 15:31
I don't get it. For me, the problem is still there with 2.8.11.
